version: '3'
services:
  case-executor-datastore:
    image: mongo:3.0.2
    networks:
      - database
  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    networks:
      - database
networks:
  database: